---

matrix:
  include:
    - os: linux
      sudo: false
      language: python
      dist: focal

before_install:
  - sudo apt-get install -y python3-pip

install:
  - pip install ansible
  - pip install ansible-lint
  - ansible-galaxy install --force git+https://github.com/deekayen/ansible-role-log-mailer.git,${TRAVIS_COMMIT}

before_script:
  - ansible --version
  - git --version
  - python --version

script:
  - ansible-lint -v .
  - ansible-playbook --syntax-check -i localhost, -c local tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
